package com.tecsup.semanaapp.ui

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage {
    SPANISH, ENGLISH
}

data class AppStrings(
    val appTitle: String,
    val loginSubtitle: String,
    val emailLabel: String,
    val passwordLabel: String,
    val showPassword: String,
    val hidePassword: String,
    val loginButton: String,
    val forgotPassword: String,
    val errEmailEmpty: String,
    val errEmailInvalid: String,
    val errPasswordEmpty: String,
    val errPasswordShort: String,
    val welcomeUser: String,
    val welcomeSubtitle: String,
    val studentDirectoryTitle: String,
    val studentDirectorySub: String,
    val myProfileTitle: String,
    val myProfileSub: String,
    val secureLogout: String,
    val studentListTitle: String,
    val studentDetailTitle: String,
    val studentIdLabel: String,
    val emailDetailLabel: String,
    val facultyLabel: String,
    val biographyLabel: String,
    val studentNotFound: String,
    val profileTitle: String,
    val personalInfoSection: String,
    val fullNameLabel: String,
    val phoneLabel: String,
    val academicSection: String,
    val careerLabel: String,
    val currentCycleLabel: String,
    val preferencesSection: String,
    val languageLabel: String,
    val spanishLang: String,
    val englishLang: String,
    val logoutButton: String
)

val SpanishStrings = AppStrings(
    appTitle = "Portal Académico",
    loginSubtitle = "Accede a tu cuenta",
    emailLabel = "Correo Institucional",
    passwordLabel = "Contraseña",
    showPassword = "Ver",
    hidePassword = "Ocultar",
    loginButton = "INICIAR SESIÓN",
    forgotPassword = "¿Olvidaste tu contraseña?",
    errEmailEmpty = "Ingresa tu correo",
    errEmailInvalid = "Correo no válido",
    errPasswordEmpty = "Ingresa tu contraseña",
    errPasswordShort = "Mínimo 6 caracteres",
    welcomeUser = "Bienvenido,\nDiego Ramos",
    welcomeSubtitle = "¿Qué deseas gestionar hoy?",
    studentDirectoryTitle = "Directorio de Alumnos",
    studentDirectorySub = "Ver y gestionar estudiantes",
    myProfileTitle = "Mi Perfil Académico",
    myProfileSub = "Datos personales y progreso",
    secureLogout = "Cerrar Sesión Segura",
    studentListTitle = "Directorio de Alumnos",
    studentDetailTitle = "Expediente Académico",
    studentIdLabel = "ID Estudiante",
    emailDetailLabel = "Correo Electrónico",
    facultyLabel = "Facultad",
    biographyLabel = "Biografía",
    studentNotFound = "Alumno no encontrado",
    profileTitle = "Configuración de Perfil",
    personalInfoSection = "INFORMACIÓN PERSONAL",
    fullNameLabel = "Nombre Completo",
    phoneLabel = "Teléfono",
    academicSection = "ACADÉMICO",
    careerLabel = "Carrera",
    currentCycleLabel = "Ciclo Actual",
    preferencesSection = "PREFERENCIAS",
    languageLabel = "Idioma",
    spanishLang = "Español",
    englishLang = "English",
    logoutButton = "Cerrar Sesión"
)

val EnglishStrings = AppStrings(
    appTitle = "Academic Portal",
    loginSubtitle = "Access your account",
    emailLabel = "Institutional Email",
    passwordLabel = "Password",
    showPassword = "Show",
    hidePassword = "Hide",
    loginButton = "LOG IN",
    forgotPassword = "Forgot your password?",
    errEmailEmpty = "Enter your email",
    errEmailInvalid = "Invalid email",
    errPasswordEmpty = "Enter your password",
    errPasswordShort = "Minimum 6 characters",
    welcomeUser = "Welcome,\nDiego Ramos",
    welcomeSubtitle = "What would you like to manage today?",
    studentDirectoryTitle = "Student Directory",
    studentDirectorySub = "View and manage students",
    myProfileTitle = "My Academic Profile",
    myProfileSub = "Personal data and progress",
    secureLogout = "Secure Log Out",
    studentListTitle = "Student Directory",
    studentDetailTitle = "Academic Record",
    studentIdLabel = "Student ID",
    emailDetailLabel = "Email Address",
    facultyLabel = "Faculty",
    biographyLabel = "Biography",
    studentNotFound = "Student not found",
    profileTitle = "Profile Settings",
    personalInfoSection = "PERSONAL INFORMATION",
    fullNameLabel = "Full Name",
    phoneLabel = "Phone",
    academicSection = "ACADEMIC",
    careerLabel = "Program",
    currentCycleLabel = "Current Semester",
    preferencesSection = "PREFERENCES",
    languageLabel = "Language",
    spanishLang = "Español",
    englishLang = "English",
    logoutButton = "Log Out"
)

val LocalAppStrings = staticCompositionLocalOf { SpanishStrings }
